### ISSUE TITLE
CIteBert Tokenizer missing

### ISSUE THREAD

**Issue by ammaarahmad1999** [copenlu/cite-worth#1]
I am trying to use citebert for sentence classification task. But it's tokenizer is missing. I am currently using SciBERT tokenizer. Please make the changes

**Comment by malteos** [comment]
Same problem here. For now I'm just using the `vocab.txt` from `scibert-scivocab-uncase` - is this the correct vocab?

**Comment by dwright37** [comment]
Sorry for the long delay on this, there is a dedicated `copenlu/citebert` tokenizer now. Alternatively, the `allenai/scibert_scivocab_uncased` tokenizer should work as well.
